version: 2
jobs:
  build:
    working_directory: ~/workspace
    macos:
      xcode: "8.3.3"
    steps:
      - checkout
      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: node install
          command: brew install node
      - run:
          name: yarn install
          command: brew install yarn
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn run pack:osx
      - run:
          name: Build
          command: yarn run pack:linux
      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
